#!/bin/bash -eux
  
cd ~/labtests/serialhub/

jlpm  &&  jlpm build
pip install -e ".[test, examples]"
jlpm  &&  jlpm build

py.test
which firefox && (( "${DISPLAY} )) && npm test

jupyter labextension uninstall -y serialhub
jupyter labextension uninstall -y .
pip uninstall serialhub
jupyter labextension install @jupyter-widgets/jupyterlab-manager --minimize=False --no-build  --debug

pip install -e ".[test, examples]"
jupyter lab  build  --dev-build=False --minimize=False --debug
